version: '3.8'

services:
  service1:
    build:
      context: ./service_1
    ports:
      - "8001:8001"
    container_name: service1
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8001/ping"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s


  service2:
    build:
      context: ./service_2
    ports:
      - "8002:8002"
    container_name: service2
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8002/ping"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx